CC=g++
ModelFolder: MongodbModel.o CIInfoChangeModel.o ServerInfoChangeModel.o \
	CIInfoIndexModel.o \
	CIModel.o DeviceModel.o \
	JsonModel.o \
	ServerModel.o ChassisModel.o \
	CoreSwitchModel.o AccessSwitchModel.o AggregationSwitchModel.o \
	CIHistoryLogModel.o ServerHistoryLogModel.o \
	DivisionHistoryLogModel.o DepartmentHistoryLogModel.o ProductHistoryLogModel.o \
	DivisionInfoChangeModel.o \
	DepartmentInfoChangeModel.o ProductInfoChangeModel.o \
	PartnerInfoModel.o NotificationModel.o \
	CollectorModel.o DivisionDefenseInfoModel.o DivisionModel.o \
	DepartmentDefenseInfoModel.o DepartmentModel.o \
	CIIndexPoolerModel.o ServerNotificationModel.o \
	DepartmentNotificationModel.o ProductNotificationModel.o \
	UserModel.o \
	MailboxModel.o \
	ServerStatisticCheckerModel.o HardwareCheckerModel.o \
	InterfaceCheckerModel.o ChassisInfoChangeModel.o ChassisHistoryLogModel.o \
	AccessSwitchHistoryLogModel.o AccessSwitchInfoChangeModel.o \
	AggregationSwitchHistoryLogModel.o AggregationSwitchInfoChangeModel.o \
	CoreSwitchHistoryLogModel.o CoreSwitchInfoChangeModel.o \
	PDUHistoryLogModel.o PDUInfoChangeModel.o \
	PeerLinkHistoryLogModel.o PeerLinkInfoChangeModel.o \
	RackHistoryLogModel.o RackInfoChangeModel.o \
	RowHistoryLogModel.o RowInfoChangeModel.o \
	PDUDefenseInfoModel.o PeerLinkDefenseInfoModel.o \
	CoreSwitchDefenseInfoModel.o AccessSwitchDefenseInfoModel.o AggregationSwitchDefenseInfoModel.o \
	RackDefenseInfoModel.o \
	RackModel.o RackServerUModel.o RackBayChassisModel.o RackSwitchModel.o \
	RackChassisModel.o RackPDUModel.o RackSwitchChassisModel.o \
	RoleOwnerModel.o TechnicalOwnerModel.o RowModel.o \
	PMMInfoChangeModel.o PMMHistoryLogModel.o
	
MongodbModel.o : MongodbModel.cpp MongodbModel.h
	$(CC) -c MongodbModel.cpp 
CIInfoChangeModel.o : CIInfoChangeModel.cpp CIInfoChangeModel.h
	$(CC) -c CIInfoChangeModel.cpp 
CIInfoIndexModel.o : CIInfoIndexModel.cpp CIInfoIndexModel.h
	$(CC) -c CIInfoIndexModel.cpp 
ServerInfoChangeModel.o : ServerInfoChangeModel.cpp ServerInfoChangeModel.h
	$(CC) -c ServerInfoChangeModel.cpp 
CIModel.o : CIModel.cpp CIModel.h
	$(CC) -c CIModel.cpp
DeviceModel.o: DeviceModel.cpp DeviceModel.h
	$(CC) -c DeviceModel.cpp
JsonModel.o : JsonModel.cpp JsonModel.h
	$(CC) -c JsonModel.cpp
ChassisModel.o : ChassisModel.cpp ChassisModel.h
	$(CC) -c ChassisModel.cpp
ServerModel.o : ServerModel.cpp ServerModel.h
	$(CC) -c ServerModel.cpp
CIHistoryLogModel.o : CIHistoryLogModel.cpp CIHistoryLogModel.h
	$(CC) -c CIHistoryLogModel.cpp 
ServerHistoryLogModel.o : ServerHistoryLogModel.cpp ServerHistoryLogModel.h
	$(CC) -c ServerHistoryLogModel.cpp 
DivisionHistoryLogModel.o : DivisionHistoryLogModel.cpp DivisionHistoryLogModel.h
	$(CC) -c DivisionHistoryLogModel.cpp 
DepartmentHistoryLogModel.o : DepartmentHistoryLogModel.cpp DepartmentHistoryLogModel.h
	$(CC) -c DepartmentHistoryLogModel.cpp 
ProductHistoryLogModel.o : ProductHistoryLogModel.cpp ProductHistoryLogModel.h
	$(CC) -c ProductHistoryLogModel.cpp 
ChassisHistoryLogModel.o: ChassisHistoryLogModel.cpp ChassisHistoryLogModel.h
	$(CC) -c ChassisHistoryLogModel.cpp
DivisionInfoChangeModel.o: DivisionInfoChangeModel.cpp DivisionInfoChangeModel.h
	$(CC) -c DivisionInfoChangeModel.cpp
DepartmentInfoChangeModel.o: DepartmentInfoChangeModel.cpp DepartmentInfoChangeModel.h
	$(CC) -c DepartmentInfoChangeModel.cpp
ProductInfoChangeModel.o: ProductInfoChangeModel.cpp ProductInfoChangeModel.h
	$(CC) -c ProductInfoChangeModel.cpp
PartnerInfoModel.o: PartnerInfoModel.cpp PartnerInfoModel.h
	$(CC) -c PartnerInfoModel.cpp
NotificationModel.o: NotificationModel.cpp NotificationModel.h
	$(CC) -c NotificationModel.cpp
CollectorModel.o: CollectorModel.cpp CollectorModel.h
	$(CC) -c CollectorModel.cpp
CIIndexPoolerModel.o: CIIndexPoolerModel.cpp CIIndexPoolerModel.h
	$(CC) -c CIIndexPoolerModel.cpp
ServerNotificationModel.o: ServerNotificationModel.cpp ServerNotificationModel.h
	$(CC) -c ServerNotificationModel.cpp
DepartmentNotificationModel.o: DepartmentNotificationModel.cpp DepartmentNotificationModel.h
	$(CC) -c DepartmentNotificationModel.cpp
ProductNotificationModel.o: ProductNotificationModel.cpp ProductNotificationModel.h
	$(CC) -c ProductNotificationModel.cpp
DivisionDefenseInfoModel.o : DivisionDefenseInfoModel.cpp DivisionDefenseInfoModel.h
	$(CC) -c DivisionDefenseInfoModel.cpp
DivisionModel.o: DivisionModel.cpp DivisionModel.h
	$(CC) -c DivisionModel.cpp
DepartmentDefenseInfoModel.o : DepartmentDefenseInfoModel.cpp DepartmentDefenseInfoModel.h
	$(CC) -c DepartmentDefenseInfoModel.cpp
DepartmentModel.o: DepartmentModel.cpp DepartmentModel.h
	$(CC) -c DepartmentModel.cpp
UserModel.o: UserModel.cpp UserModel.h
	$(CC) -c UserModel.cpp
ServerStatisticCheckerModel.o: ServerStatisticCheckerModel.cpp ServerStatisticCheckerModel.h
	$(CC) -c ServerStatisticCheckerModel.cpp
HardwareCheckerModel.o: HardwareCheckerModel.cpp HardwareCheckerModel.h
	$(CC) -c HardwareCheckerModel.cpp
InterfaceCheckerModel.o: InterfaceCheckerModel.cpp InterfaceCheckerModel.h
	$(CC) -c InterfaceCheckerModel.cpp
ChassisInfoChangeModel.o: ChassisInfoChangeModel.cpp ChassisInfoChangeModel.h
	$(CC) -c ChassisInfoChangeModel.cpp
AccessSwitchHistoryLogModel.o: AccessSwitchHistoryLogModel.cpp AccessSwitchHistoryLogModel.h
	$(CC) -c AccessSwitchHistoryLogModel.cpp
AccessSwitchInfoChangeModel.o: AccessSwitchInfoChangeModel.cpp AccessSwitchInfoChangeModel.h
	$(CC) -c AccessSwitchInfoChangeModel.cpp
AggregationSwitchHistoryLogModel.o: AggregationSwitchHistoryLogModel.cpp AggregationSwitchHistoryLogModel.h
	$(CC) -c AggregationSwitchHistoryLogModel.cpp
AggregationSwitchInfoChangeModel.o: AggregationSwitchInfoChangeModel.cpp AggregationSwitchInfoChangeModel.h
	$(CC) -c AggregationSwitchInfoChangeModel.cpp
CoreSwitchHistoryLogModel.o: CoreSwitchHistoryLogModel.cpp CoreSwitchHistoryLogModel.h
	$(CC) -c CoreSwitchHistoryLogModel.cpp
CoreSwitchInfoChangeModel.o: CoreSwitchInfoChangeModel.cpp CoreSwitchInfoChangeModel.h
	$(CC) -c CoreSwitchInfoChangeModel.cpp
PDUHistoryLogModel.o: PDUHistoryLogModel.cpp PDUHistoryLogModel.h
	$(CC) -c PDUHistoryLogModel.cpp
PDUInfoChangeModel.o: PDUInfoChangeModel.cpp PDUInfoChangeModel.h
	$(CC) -c PDUInfoChangeModel.cpp
PeerLinkHistoryLogModel.o: PeerLinkHistoryLogModel.cpp PeerLinkHistoryLogModel.h
	$(CC) -c PeerLinkHistoryLogModel.cpp
PeerLinkInfoChangeModel.o: PeerLinkInfoChangeModel.cpp PeerLinkInfoChangeModel.h
	$(CC) -c PeerLinkInfoChangeModel.cpp
RackHistoryLogModel.o: RackHistoryLogModel.cpp RackHistoryLogModel.h
	$(CC) -c RackHistoryLogModel.cpp
RackInfoChangeModel.o: RackInfoChangeModel.cpp RackInfoChangeModel.h
	$(CC) -c RackInfoChangeModel.cpp
RowHistoryLogModel.o: RowHistoryLogModel.cpp RowHistoryLogModel.h
	$(CC) -c RowHistoryLogModel.cpp
RowInfoChangeModel.o: RowInfoChangeModel.cpp RowInfoChangeModel.h
	$(CC) -c RowInfoChangeModel.cpp
PDUDefenseInfoModel.o: PDUDefenseInfoModel.cpp PDUDefenseInfoModel.h
	$(CC) -c PDUDefenseInfoModel.cpp
PeerLinkDefenseInfoModel.o: PeerLinkDefenseInfoModel.cpp PeerLinkDefenseInfoModel.h
	$(CC) -c PeerLinkDefenseInfoModel.cpp
CoreSwitchDefenseInfoModel.o: CoreSwitchDefenseInfoModel.cpp CoreSwitchDefenseInfoModel.h
	$(CC) -c CoreSwitchDefenseInfoModel.cpp
AccessSwitchDefenseInfoModel.o: AccessSwitchDefenseInfoModel.cpp AccessSwitchDefenseInfoModel.h
	$(CC) -c AccessSwitchDefenseInfoModel.cpp 
AggregationSwitchDefenseInfoModel.o: AggregationSwitchDefenseInfoModel.cpp AggregationSwitchDefenseInfoModel.h
	$(CC) -c AggregationSwitchDefenseInfoModel.cpp
RackDefenseInfoModel.o: RackDefenseInfoModel.cpp RackDefenseInfoModel.h
	$(CC) -c RackDefenseInfoModel.cpp
CoreSwitchModel.o : CoreSwitchModel.cpp CoreSwitchModel.h
	$(CC) -c CoreSwitchModel.cpp 
AccessSwitchModel.o : AccessSwitchModel.cpp AccessSwitchModel.h
	$(CC) -c AccessSwitchModel.cpp 
AggregationSwitchModel.o : AggregationSwitchModel.cpp AggregationSwitchModel.h
	$(CC) -c AggregationSwitchModel.cpp 
RackModel.o: RackModel.cpp RackModel.h
	$(CC) -c RackModel.cpp
RackServerUModel.o: RackServerUModel.cpp RackServerUModel.h
	$(CC) -c RackServerUModel.cpp
RackBayChassisModel.o: RackBayChassisModel.cpp RackBayChassisModel.h
	$(CC) -c RackBayChassisModel.cpp
RackSwitchModel.o: RackSwitchModel.cpp RackSwitchModel.h
	$(CC) -c RackSwitchModel.cpp
RackChassisModel.o: RackChassisModel.cpp RackChassisModel.h
	$(CC) -c RackChassisModel.cpp
RackPDUModel.o: RackPDUModel.cpp RackPDUModel.h
	$(CC) -c RackPDUModel.cpp
RackSwitchChassisModel.o : RackSwitchChassisModel.cpp RackSwitchChassisModel.h
	$(CC) -c RackSwitchChassisModel.cpp 	
RoleOwnerModel.o: RoleOwnerModel.cpp RoleOwnerModel.h
	$(CC) -c RoleOwnerModel.cpp
TechnicalOwnerModel.o: TechnicalOwnerModel.cpp TechnicalOwnerModel.h
	$(CC) -c TechnicalOwnerModel.cpp
RowModel.o : RowModel.cpp RowModel.h
	$(CC) -c RowModel.cpp 	
PMMInfoChangeModel.o: PMMInfoChangeModel.cpp PMMInfoChangeModel.h
	$(CC) -c PMMInfoChangeModel.cpp
PMMHistoryLogModel.o: PMMHistoryLogModel.cpp PMMHistoryLogModel.h
	$(CC) -c PMMHistoryLogModel.cpp

clean:
	rm -rf *o ModelFolder
