CC=g++
UtilitiesFolder: Utilities.o DBUtilities.o
Utilities.o: Utilities.cpp Utilities.h
	$(CC) -c Utilities.cpp
DBUtilities.o: DBUtilities.cpp DBUtilities.h
	$(CC) -c DBUtilities.cpp
clean:
	rm -rf *o UtilitiesFolder
