/* soapClient.c
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.16 2014-03-06 03:09:25 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Call(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Call *ns1__Call, struct _ns1__CallResponse *ns1__CallResponse)
{	struct __ns1__Call soap_tmp___ns1__Call;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://sdk_webservice:8013/SDKService.svc";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ISDKService/Call";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Call.ns1__Call = ns1__Call;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize___ns1__Call(soap, &soap_tmp___ns1__Call);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Call(soap, &soap_tmp___ns1__Call, "-ns1:Call", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Call(soap, &soap_tmp___ns1__Call, "-ns1:Call", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CallResponse)
		return soap_closesock(soap);
	soap_default__ns1__CallResponse(soap, ns1__CallResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CallResponse(soap, ns1__CallResponse, "ns1:CallResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
